AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Commodity
Globals:
  Function:
    Timeout: 3
Resources:
  CommodityFunctions:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://commodity-sam/c9b199f707e8add9f8bb3f9e4f74d3ad
      Handler: app.lambdaHandler
      Runtime: nodejs12.x
      Policies:
      - DynamoDBWritePolicy:
          TableName: Commodity
      Events:
        form:
          Type: Api
          Properties:
            Path: /commodity
            Method: post
  CommodityProviderByIdFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://commodity-sam/1725e7de1f2c94fc9576d75540b8d607
      Handler: app.lambdaHandler
      Runtime: nodejs12.x
      Policies:
      - DynamoDBReadPolicy:
          TableName: Commodity
      Events:
        form:
          Type: Api
          Properties:
            Path: /commodity/{commodityId}
            Method: get
  CommoditiesProviderByCommodityTypeFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://commodity-sam/d59ce1d6c379cd0c1aa3b0a3b46b7bf6
      Handler: app.lambdaHandler
      Runtime: nodejs12.x
      Policies:
      - DynamoDBReadPolicy:
          TableName: Commodity
      Events:
        form:
          Type: Api
          Properties:
            Path: /commodities/{commodityType}
            Method: get
Outputs:
  CommodityApi:
    Description: API Gateway endpoint URL for Prod stage for Commodity functions
    Value:
      Fn::Sub: https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/commodity
  CommodityFunctions:
    Description: Commodity Lambda Functions ARN
    Value:
      Fn::GetAtt:
      - CommodityFunctions
      - Arn
  CommodityFunctionsIamRole:
    Description: Implicit IAM Role created for Commodity functions
    Value:
      Fn::GetAtt:
      - CommodityFunctionsRole
      - Arn
