AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: CommodityForm
Globals:
  Function:
    Timeout: 3
Resources:
  CommodityFormFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://commodity-sam/3baff0bb6bcb004c882f1ebc19af5819
      Handler: app.lambdaHandler
      Runtime: nodejs12.x
      Policies:
      - DynamoDBWritePolicy:
          TableName: Commodity
      Events:
        form:
          Type: Api
          Properties:
            Path: /form
            Method: get
Outputs:
  CommodityFormApi:
    Description: API Gateway endpoint URL for Prod stage for CommodityForm function
    Value:
      Fn::Sub: https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/form/
  CommodityFormFunction:
    Description: CommodityForm Lambda Function ARN
    Value:
      Fn::GetAtt:
      - CommodityFormFunction
      - Arn
  CommodityFormFunctionIamRole:
    Description: Implicit IAM Role created for CommodityForm function
    Value:
      Fn::GetAtt:
      - CommodityFormFunctionRole
      - Arn
