AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: "Commodity"
Globals:
  Function:
    Timeout: 3

Resources:
  CommodityFunctions:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: addCommodity/
      Handler: app.lambdaHandler
      Runtime: nodejs12.x
      Policies:
        - DynamoDBWritePolicy:
            TableName: Commodity
      Events:
        form:
          Type: Api
          Properties:
            Path: /commodity
            Method: post
  CommodityProviderFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: commodityProviderById/
      Handler: app.lambdaHandler
      Runtime: nodejs12.x
      Policies:
        - DynamoDBReadPolicy:
            TableName: Commodity
      Events:
        form:
          Type: Api
          Properties:
            Path: /commodity/{commodityId}
            Method: get

Outputs:
  CommodityApi:
    Description: "API Gateway endpoint URL for Prod stage for Commodity functions"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/commodity"
  CommodityFunctions:
    Description: "Commodity Lambda Functions ARN"
    Value: !GetAtt CommodityFunctions.Arn
  CommodityFunctionsIamRole:
    Description: "Implicit IAM Role created for Commodity functions"
    Value: !GetAtt CommodityFunctionsRole.Arn
