AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: "CommodityForm"
Globals:
  Function:
    Timeout: 3

Resources:
  CommodityFormFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: form/
      Handler: app.lambdaHandler
      Runtime: nodejs12.x
      Policies:
        - DynamoDBWritePolicy:
            TableName: Commodity
      Events:
        form:
          Type: Api
          Properties:
            Path: /form
            Method: post

Outputs:
  CommodityFormApi:
    Description: "API Gateway endpoint URL for Prod stage for CommodityForm function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/form/"
  CommodityFormFunction:
    Description: "CommodityForm Lambda Function ARN"
    Value: !GetAtt CommodityFormFunction.Arn
  CommodityFormFunctionIamRole:
    Description: "Implicit IAM Role created for CommodityForm function"
    Value: !GetAtt CommodityFormFunctionRole.Arn
